name: NorseCommunityPlugin
version: '${project.version}'
main: norsecommunityplugin.norsecommunityplugin.NorseCommunityPlugin
api-version: '1.20'
commands:
  setspawn:
    description: Sets the spawn
    usage: /setspawn
    permission: norsecommunityplugin.setspawn
  spawn:
    description: Teleports you to the spawn
    usage: /spawn
    permission: norsecommunityplugin.spawn
  nationmenu:
    description: Opens the nation menu
    usage: /nationmenu
    permission: norsecommunityplugin.nationmenu
  neverrainagain:
    description: Never rains again
    usage: /neverrainagain
    permission: norsecommunityplugin.neverrainagain

  dagger:
    description: Gives you a dagger
    usage: /dagger
    permission: norsecommunityplugin.dagger

  removeblackstone:
    description: Removes blackstone
    usage: /removeblackstone <player>
    permission: norsecommunityplugin.removeblackstone

  classmenu:
    description: Opens the class menu
    usage: /classmenu
    permission: norsecommunityplugin.class

  stats:
    description: Shows your stats
    usage: /stats <player> or /stats
    permission: norsecommunityplugin.stats

  sethp:
    description: Sets the health of a player
    usage: /sethp <player> <health>
    permission: norsecommunityplugin.sethp

  setdamage:
    description: Sets the damage of a player
    usage: /setdamage <player> <damage>
    permission: norsecommunityplugin.setdamage

  setprotection:
    description: Sets the protection of a player
    usage: /setprotection <player> <protection>
    permission: norsecommunityplugin.setprotection

  setdexterity:
    description: Sets the dexterity of a player
    usage: /setdexterity <player> <dexterity>
    permission: norsecommunityplugin.setdexterity

  setclass:
    description: Sets the class of a player
    usage: /setclass <player> <class>
    permission: norsecommunityplugin.setclass